INSERT INTO MUNICIPIO (ID, MUNICIPIO, ) VALUES
(41, 'Mixquiahuala'),
(42, 'Molango de Escamilla');


INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2174,'Tepeitic',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2175,'El Calvario',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2176,'3 de Mayo',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2177,'La Peña',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2178,'Taxhuada',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2179,'Danfhi',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2180,'Los Tigres',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2181,'Centro',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2182,'La Vega',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2183,'El Bondho',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2184,'Reforma',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2185,'La Estación',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2186,'Mixquiahuala',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2187,'Veracruz',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2188,'Dos Cerros',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2189,'Jagüey Blanco',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2190,'El Durazno',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2191,'Benito Juárez',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2192,'Hacienda Vieja',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2193,'El Rodeo Grande',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2194,'La Arboleda',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2195,'Árbol Grande',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2196,'El Rodeo',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2197,'Viborillas',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2198,'El Cerrito',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2199,'Morelos (El Nueve)',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2200,'Palmillas',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2201,'Monte Grande',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2202,'Motobatha',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2203,'Los Higos',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2204,'Los Colorines',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2205,'Palo Seco',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2206,'Cinta Larga Sección 22',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2207,'Cañada',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2208,'Los Ángeles',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2209,'Teñhe',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2210,'El Palomar',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (2211,'Carrillo Puerto',41);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3460,'Santa Cruz',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3461,'Molango Centro',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3462,'Los Sabinos',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3463,'El Plan (Barrio Nuevo)',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3464,'Piedras Negras',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3465,'Ixmolintla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3466,'Tepetlanixco',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3467,'El Balcón',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3468,'Tlalaquia',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3469,'La Garita',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3470,'Cuatlacalca',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3471,'El Calvario',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3472,'Atezca',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3473,'Tzacatzonco',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3474,'Pemuxtitla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3475,'Puerto Tlamaxa',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3476,'Tepeco',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3477,'Satiopa (Rancho Nahuiopan)',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3478,'Ohuezco',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3479,'Zacatempa',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3480,'San Miguel',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3481,'Alameda',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3482,'Tejería',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3483,'San Bernardo',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3484,'Olotlilla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3485,'Nopayahuatl',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3486,'Tepetlapa',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3487,'Acoyotla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3488,'Tenango',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3489,'Chicoyotla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3490,'Tecuaqueo',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3491,'Zacuala (Huixquilico)',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3492,'Ixcotla (Nuevo Ixcotla)',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3493,'Cuacomol',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3494,'Tehuizco',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3495,'Acatla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3496,'Xicalango',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3497,'Tetipanchalco',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3498,'Acatitla',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3499,'Naopa',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3500,'Chayahual',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3501,'Acayuca',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3502,'Mina 300 (Ixtapalapa)',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3503,'Xuchitlán',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3504,'Ixcatlán (San Pedro)',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3505,'San Antonio',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3506,'Ixcuicuila',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3507,'Cuxhuacan',42);
INSERT INTO LOCALIDAD (id,localidad,municipio_id) VALUES (3508,'Tlatzintla',42);
